[package]
name = "YetAnotherWordleCloneBackend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rand = "0.9.0"
chrono = "0.4"
serde = {version =  "1.0.219", features = ["derive"] }